AllCops:
  Exclude:
    - "bin/**/*"
    - "twilito.gemspec"
  AllCops:
    TargetRubyVersion: 3.2

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Style/StringLiterals:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/Documentation:
  Enabled: false
